services:
  redis:
    image: redis:alpine
    container_name: login_panel_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_storage:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: login_panel_app
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=enterprise_super_secure_jwt_secret_key_minimum_32_characters_2026!
    depends_on:
      - redis

volumes:
  redis_storage:
